# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmodel', '0002_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='sid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
