# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmodel', '0003_channel_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='bitrate',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='pcr_period',
            field=models.IntegerField(default=27),
            preserve_default=False,
        ),
    ]
