# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmodel', '0004_auto_20160821_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='status',
            field=models.IntegerField(),
        ),
    ]
