# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmodel', '0005_auto_20160826_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='ffmpeg_pid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='parse_pid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
